u

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -366,7 +366,51 @@ jobs:
             echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
-
+  smoke-test:
+    docker: 
+      - image: python:3.11-rc-alpine
+    steps:
+      - checkout
+      # - run: 
+      #     name: Install dependencies
+      #     command: |
+      #       apk add --update ansible curl nodejs npm
+      #       apk add --no-cache aws-cli
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+            echo ID ${CIRCLE_WORKFLOW_ID:0:7}
+            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:project,Values=udapeople" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
+            echo $BACKEND_IP
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"  
+      - run:
+          name: Backend smoke test
+          command: |
+            echo "Wait for backend to become available..."
+            sleep 30s
+            echo "Attempting to reach backend..."
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              echo "Backend status OK"
+              exit 0
+            else
+              echo "Backend status NOT OK"
+              exit 1
+            fi
+      # - run:
+      #     name: Frontend Smoke Test 
+      #     command: |
+      #       URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+      #       echo ${URL} 
+      #       if curl -s ${URL} | grep "Welcome"
+      #       then
+      #           # Change this to 0 after the job fails
+      #         return 0
+      #       else
+      #         return 1
+      #       fi
             
 workflows:
   default:
@@ -395,6 +439,8 @@ workflows:
       # - deploy-frontend:
       #     requires: 
       #       - deploy-infrastructure
-      - Saving-Ip-EC2
-      - deploy-backend:
-          requires: [Saving-Ip-EC2]
+      # - Saving-Ip-EC2
+      # - deploy-backend:
+      #     requires: [Saving-Ip-EC2]
+
+      - smoke-test
