u

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,28 +25,28 @@ commands:
             aws configure set aws_session_token $AWS_SESSION_TOKEN
             aws configure set region $AWS_DEFAULT_REGION
 jobs:
-  build-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: Build front-end
-          command: |
-            cd frontend
-            npm install
-            npm run build
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-build
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
-      - slack/notify:
-          event: pass
-          template: success_tagged_deploy_1
+  # build-frontend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [frontend-build]
+  #     - run:
+  #         name: Build front-end
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           npm run build
+  #     - save_cache:
+  #         paths: [frontend/node_modules]
+  #         key: frontend-build
+      # - slack/notify:
+      #     event: fail
+      #     template: basic_fail_1
+      # - slack/notify:
+      #     event: pass
+      #     template: success_tagged_deploy_1
   
   build-backend:
     docker:
@@ -62,16 +62,15 @@ jobs:
             ls -la
             npm install 
             npm run build
-    
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
-      - slack/notify:
-          event: pass
-          template: success_tagged_deploy_1
+      # - slack/notify:
+      #     event: fail
+      #     template: basic_fail_1
+      # - slack/notify:
+      #     event: pass
+      #     template: success_tagged_deploy_1
   
   # build-backend:
   #   docker:
@@ -133,19 +132,19 @@ jobs:
       #     event: pass
       #     template: success_tagged_deploy_1
 
-  scan-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout 
-      - restore_cache: 
-          keys: [scan-frontend]
-      - run:
-          name: Scan frontend 
-          command: |
-            cd frontend
-            npm install
-            npm audit fix --audit-level=critical
+  # scan-frontend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout 
+  #     - restore_cache: 
+  #         keys: [scan-frontend]
+  #     - run:
+  #         name: Scan frontend 
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           npm audit fix --audit-level=critical
       # - slack/notify:
       #     event: fail
       #     template: basic_fail_1
@@ -366,82 +365,70 @@ jobs:
             echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
-  smoke-test:
-    docker: 
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      # - run: 
-      #     name: Install dependencies
-      #     command: |
-      #       apk add --update ansible curl nodejs npm
-            # apk add --no-cache aws-cli
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            echo ID ${CIRCLE_WORKFLOW_ID:0:7}
-            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:project,Values=udapeople" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
-            echo $BACKEND_IP
-            export API_URL="http://${BACKEND_IP}:3030"
+
+  # smoke-test:
+  #   docker: 
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     - checkout
+  #     # - run: 
+  #     #     name: Install dependencies
+  #     #     command: |
+  #     #       apk add --update ansible curl nodejs npm
+  #           # apk add --no-cache aws-cli
+  #     - run:
+  #         name: Get backend url
+  #         command: |
+  #           # your code here
+  #           echo ID ${CIRCLE_WORKFLOW_ID:0:7}
+  #           export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:project,Values=udapeople" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
+  #           echo $BACKEND_IP
+  #           export API_URL="http://${BACKEND_IP}:3030"
             
-      - run:
-          name: Backend smoke test
-          command: |
-            # echo "Wait for backend to become available..."
-            # sleep 30s
-            # echo "Attempting to reach backend..."
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-              echo "Backend status OK"
-              exit 0
-            else
-              echo "Backend status NOT OK"
-              exit 1
-            fi
-      - run:
-          name: Frontend Smoke Test 
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-                # Change this to 0 after the job fails
-              return 1
-            else
-              return 1
-            fi
+  #     - run:
+  #         name: Backend smoke test
+  #         command: |
+  #           # echo "Wait for backend to become available..."
+  #           # sleep 30s
+  #           # echo "Attempting to reach backend..."
+  #           echo "${API_URL}/api/status"
+  #           if curl "${API_URL}/api/status" | grep "ok"
+  #           then
+  #             echo "Backend status OK"
+  #             exit 0
+  #           else
+  #             echo "Backend status NOT OK"
+  #             exit 1
+  #           fi
+  #     - run:
+  #         name: Frontend Smoke Test 
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+  #           echo ${URL} 
+  #           if curl -s ${URL} | grep "Welcome"
+  #           then
+  #               # Change this to 0 after the job fails
+  #             return 1
+  #           else
+  #             return 1
+  #           fi
             
 workflows:
   default:
     jobs:
-      # - deploy-infrastructure
-      # - Saving-Ip-EC2
-      # - configure-infrastructure:
-      #     requires: [Saving-Ip-EC2]
-      # - build-frontend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
+      
       # - build-backend
       # - test-backend:
-      #     requires: [build-backend]
+      #     requires : [build-backend]
       # - scan-backend:
-      #     requires: [build-backend]
-      # - run-migrations:
+      #     requires : [test-backend]
+      # - configure-infrastructure:
       #     requires: [scan-backend]
-      # - run-migrations
-      # - build-backend
-
-
-      # - deploy-infrastructure
-      # - deploy-frontend:
-      #     requires: 
-      #       - deploy-infrastructure
-      # - Saving-Ip-EC2
+      # - deploy-infrastructure:
+      #     requires : [configure-backend]
+      # - run-migrations:
+      #     requires : [deploy-infrastructure]
       # - deploy-backend:
-      #     requires: [Saving-Ip-EC2]
+      #     requires : [run-migrations]
 
-      - smoke-test
+      - run-migrations
